### ISSUE TITLE
Support older glibc versions even when built using newer ones

### ISSUE THREAD

**Issue by ronaldtse** [tamatebako/tebako#53] opened 2021-12-16 09:17 UTC
From @maxirmx:

A binary built on Ubuntu 20.04 will **not** work on a vanilla Ubuntu 18.04 right now.

The status today is as follows:

- A binary built on Ubuntu 18.04 will work on Ubuntu 20.04.  It is tested now but I use GHA images. I can probably deploy  clean Ubuntu container to make it "more vanilla".

- However,  a  binary built on Ubuntu 20.04 WILL NOT WORK on Ubuntu 18.04  since I am linking shared glibc as ruby-packer does.  There are some options to make 20.04 image work on 18.04 if we need it. 

* https://github.com/wheybags/glibc_version_header
* https://github.com/crosstool-ng/crosstool-ng

Overview: 
* https://stackoverflow.com/questions/2856438/how-can-i-link-to-a-specific-glibc-version

From: https://github.com/wheybags/glibc_version_header

<img width="264" alt="Screenshot 2021-12-16 at 5 14 03 PM" src="https://user-images.githubusercontent.com/11865/146342578-1c30d1ac-3b78-4199-aa32-c5cbd44c9255.png">

We probably want to support CentOS >= 7 so we will need to tag that version if we use glibc_version_header.

_Originally posted by @maxirmx in https://github.com/metanorma/packed-mn/issues/126#issuecomment-995113970_

**Comment by ronaldtse** [comment] 2024-08-17 13:20
Wow an issue from 2021! Finally time to get this done 😜

**Comment by maxirmx** [comment] 2024-09-01 17:15
The approach proposed in this issue was based on my wrong understanding of the root cause.
It works the other way round, it is possible to support newer glibc versions if build on older ones with some limitations caused by private ABI. In metanorma we had package built on Ubuntu 18 that was compatible with Ubuntu 20.

I am closing this issue in favour of https://github.com/tamatebako/tebako/issues/196

**Closed by maxirmx** 2024-09-01 17:15 UTC
Labels: enhancement
